server:
  port:
    8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VladimirPoddubchak/SferaConfigServer
          search-paths:
            - 'service-config/*service'
